config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", :as => :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", :as => :pwa_manifest

  # Defines the root path route ("/")
  root "engine#index"

  resources :job
  resources :job_seekers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_seekers/job_seeker.rb
# frozen_string_literal: true

module JobSeekers
  class JobSeeker < ApplicationRecord
    has_many :job_seeker_skills
  end
end

app/models/job_seekers/job_seeker_skill.rb
# frozen_string_literal: true

module JobSeekers
  class JobSeekerSkill < ApplicationRecord
    belongs_to :job_seeker
  end
end

app/models/jobs/job.rb
# frozen_string_literal: true

module Jobs
  class Job < ApplicationRecord
    has_many :job_required_skills, class_name: "Jobs::JobRequiredSkill"
  end
end

app/models/jobs/job_required_skill.rb
# frozen_string_literal: true

module Jobs
  class JobRequiredSkill < ApplicationRecord
    belongs_to :job, class_name: "Jobs::Job"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/engine_controller.rb
class EngineController < ApplicationController
  def index
    @job_match_array = Engine::Queries::JobMatching.new.call
  end
end

app/controllers/job_controller.rb
class JobController < ApplicationController
  def index
    @jobs = Jobs::Queries::GetAll.new.call
  end

  def create
    Jobs::Command::CreateFromCsv.new.execute(params[:job])

    redirect_to(root_path, notice: "Jobs Created")
  rescue ActiveRecord::RecordNotUnique
    redirect_to(root_path, alert: "Jobs Id Existed")
  end
end

app/controllers/job_seekers_controller.rb
class JobSeekersController < ApplicationController
  def index
    @job_seekers = JobSeekers::Queries::GetAll.new.call
  end

  def create
    JobSeekers::Command::CreateFromCsv.new.execute(params[:job_seeker])

    redirect_to(root_path, notice: "Job Seekers Created")
  rescue ActiveRecord::RecordNotUnique
    redirect_to(root_path, alert: "Job Seekers Id Existed")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/engine/index.html.erb
<div class="row pt-3">
  <div class="row">
    <h1>Jobs CSV Upload</h1>
  </div>

  <div class="row pt-2">
    <%= form_tag job_index_path, method: "post", action: "upload", multipart: true do %>
      <%= file_field_tag 'job' %>
      <%= submit_tag "Upload Jobs", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row pt-3">
  <div class="row">
    <h1>Job Seeker CSV Upload</h1>
  </div>

  <div class="row pt-2">
    <%= form_tag job_seekers_path, method: "post", action: "upload", multipart: true do %>
      <%= file_field_tag 'job_seeker' %>
      <%= submit_tag "Upload Job Seekers", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<div class="row py-3">
  <div class="row">
    <h1>Jobs Matches</h1>
  </div>

  <div class="row pt-2">
    <table class="table table-striped table-bordered">
      <tr>
        <th>Job Seeker Id</th>
        <th>Job Seeker Name</th>
        <th>Job Id</th>
        <th>Job Title</th>
        <th>Matching Skill Count</th>
        <th>Matching Skill Percent</th>
      </tr>
      <% @job_match_array.each do |job_match| %>
        <tr>
          <td><%= job_match[:jobseeker_id] %></td>
          <td><%= job_match[:jobseeker_name] %></td>
          <td><%= job_match[:job_id] %></td>
          <td><%= job_match[:job_title] %></td>
          <td><%= job_match[:matching_skill_count] %></td>
          <td><%= job_match[:matching_skill_percent] %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="row">
  <div class="col">
    <%= link_to "Jobs List", job_index_path, class: "btn btn-primary btn-lg" %>
  </div>
  <div class="col">
    <%= link_to "Job Seekers List", job_seekers_path, class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/job/index.html.erb
<div class="row">
  <h1>Jobs List</h1>
</div>

<div class="row">
  <table class="table table-striped table-bordered">
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Required Skills</th>
    </tr>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job[:id] %></td>
        <td><%= job[:title] %></td>
        <td><%= job[:required_skills] %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/job_seekers/index.html.erb
<div class="row">
  <h1>Job Seekers List</h1>
</div>

<div class="row">
  <table class="table table-striped table-bordered">
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Skills</th>
    </tr>
    <% @job_seekers.each do |job_seeker| %>
      <tr>
        <td><%= job_seeker[:id] %></td>
        <td><%= job_seeker[:name] %></td>
        <td><%= job_seeker[:skills] %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Job Match Engine" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-brand">
          <a class="navbar-item btn btn-primary" href="<%= root_path %>">
            Home
          </a>
        </div>
      </div>
    </nav>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-primary">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>